### ISSUE TITLE
ラップする機能をつけたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-dynamic-if-block#25]
毎回 Dynamic If ブロックを配置してから中に入れるのが面倒。
最近 VK Blocks のアニメーションブロックとかで対応されたのでそのプルリクを見ればわかるかと。

**Comment by doshimaf** [comment]
対応します。

**Comment by doshimaf** [comment]
https://github.com/vektor-inc/vk-blocks-pro/pull/1681

**Comment by doshimaf** [comment]
リリース済につきclose
