### ISSUE TITLE
カスタムフィールドの値の大なり小なりでの条件分岐がしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-dynamic-if-block#26]
想定要素 : カスタムフィールドに日付を入れて、その日付になると自動的に非表示になるなど

**Comment by doshimaf** [comment]
@kurudrive 
内部の処理の実装はまだですが、取り急ぎUI部分を作ってみました。

**Comment by kurudrive** [comment]
@doshimaf ありがとうございます。

deadline は more/less で対応できるのではないかと思いますがどうでしょう（・ｗ・？

**Comment by doshimaf** [comment]
@kurudrive 
たしかにそうですね。more/lessのみで進めます。

**Comment by doshimaf** [comment]
@kurudrive 
大なり小なりのときの比較対象の値はNumberControlコンポーネントにしていますが、これがデフォルトだとNumber型のみとなり、日付を入れることができません。
なので、型を指定しないようにしましたが良いでしょうか？

**Comment by kurudrive** [comment]
@doshimaf とりあえず一旦それで進めてくださいー。後で動作確認しますー。

**Comment by doshimaf** [comment]
@kurudrive 
取り急ぎ、数値に対する大なり小なりの条件分岐の処理を追加しました。

**Comment by doshimaf** [comment]
@kurudrive 
> 想定要素 : カスタムフィールドに日付を入れて、その日付になると自動的に非表示になるなど

こちらやはり数値の大小とは別で設けたほうが良いのではないでしょうか？
というのも、カスタムフィールドに日付を入れて、その日付を比較するとなると、比較したい数値は不要ですし、大なり小なりとは別ものになると思います。

**Comment by doshimaf** [comment]
@kurudrive 
使い勝手的に数値と日付は分けたほうが使いやすそうだったので、分けて実装してみました。
触ってみて数値のみのほうが使いやすければそちらに戻しますので、確認をお願いいたします。

**Comment by kurudrive** [comment]
@doshimaf 解説しよう（・ｗ・
日付に分けた場合、何が起こるかというと、日付のカスタムフィールドに
* 2023/03/17 
* 17/03/2023
* 2023年3月17日
などで保存されると、それをGMTに変換しないと、期間の前なのか後なのか判断できないという事態になります。

日付を設定するなら、「日付の保存形式は Ymd に必ずしてください」などの注意書きがないと厳しいかなという印象。

**Comment by doshimaf** [comment]
- 数値バージョンと日付バージョンを分けてPRに
- 日付バージョンは時間まで対応
- deadlineとstartlineに対応させる
- 時間が指定されているかどうかによってそれぞれ時間を自動設定（00:00 or 23:59）
- 数値バージョンは必要になるまで保留し日付バージョンを優先

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-blocks-pro/issues/1695#issuecomment-1650721077

@doshimaf ごめんなさい、大嶋君...。いや、僕も使ってみてなんとなく違和感はあったんよ。
deadline と startline を指定するためにカスタムフィールドを別途用意しないといけないという工程が。
カスタムフィールドありきで考えてしまったのでいけなかったです...。

これ、カスタムフィールドとは全く別で、
「表示期間」という項目の select があって

* startline
* deadline
* 公開日からの日数

という option を用意して、startline か deadline だったらカレンダーからの日付入力
公開日からの日数 だったら 日数を数値入力 の方がカスタムフィールドわざわざ作らなくても良いから、システム的にもユーザーの使い勝手的にも良いと思いますがどうでしょう....。

ご...ごめんなさい...。

**Comment by kurudrive** [comment]
あー、カスタムフィールドの方が都合いいケースもあるかも...

**Comment by doshimaf** [comment]
@kurudrive 
僕もカスタムフィールド前提で考えていたので、カスタムフィールドなしでということであれば、そのほうが圧倒的に使いやすいと思います！
ということで、表示期間設定の項目を追加する方向に変更しますが、選択肢は、
- 指定しない
- startline
- deadline
- 公開日からの日数
ということで良いでしょうか？

**Comment by doshimaf** [comment]
startline か deadline だったら「カレンダーからの日付入力」or「カスタムフィールド指定」

**Comment by kurudrive** [comment]
表示期間

* 指定しない
* startline
* deadline
* 公開日からの日数

表示期間の指定方法

* このブロックで直接入力
* カスタムフィールドの値を参照

---

■ このブロックで直接入力の場合

startline か deadline の場合はカレンダーで指定
公開日からの日数の場合は数値入力

■ カスタムフィールドの値を参照の場合

[ フィールド名 ]
startline か deadline の場合は Y-m-d H:i で保存してください。
公開日からの日数の場合は整数で保存してください。

**Comment by osmdik** [comment]
リリース済のためclose
