### ISSUE TITLE
ユーザー権限での条件分岐

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-dynamic-if-block#27]
特定のユーザー権限の人のみ見れるコンテンツなどでの利用を想定

* 存在するユーザー権限（管理者・編集者ほかユーザーが独自に発行した権限など）を自動取得する

懸念点
* 編集者以上 とか 何を持って○○以上とするのか判断するか悩ましい

**Comment by doshimaf** [comment]
リリース済のためclose
