### ISSUE TITLE
日付検索で カスタムフィールド参照&カスタムフィールド名未指定 の場合に Fatal error になる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-dynamic-if-block#39]
1. サイトエディタを開く
2. テンプレートファイルに Dynamic If ブロックを配置してカスタムフィールド参照&カスタムフィールド名未指定で保存
3. 該当テンプレートが表示されるページを表示
4. Fatal error

- [x] カスタムフィールドの値が未入力の場合 -> 表示
- [x] カスタムフィールドが未入力の場合は「参照するカスタムフィールド名を入力してください」のアラートを表示
- [x] カスタムフィールドに入力された値が日付のフォーマットじゃない値だった場合 -> 表示

**Comment by kurudrive** [comment]
@osmdik よろしくお願いいたします (￣人￣)

**Comment by osmdik** [comment]
@kurudrive 
調整しましたので、確認をお願いいたします。

**Comment by osmdik** [comment]
リリース済のためclose
